# Generated by Django 4.0.5 on 2022-06-06 03:53

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_tag_options_rename_tag_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=post.models.user_directory_path, verbose_name='picture'),
        ),
    ]
