# Generated by Django 4.0.5 on 2022-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=10000, verbose_name='caption'),
        ),
    ]
